project_id = "ewaarsfeolhcfzenahqj"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev", "http://localhost:3000", "https://659910ed-16a1-4aea-89d7-64e391080b25.lovableproject.com"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true

[db]
port = 54322

[functions.apply-wallet-discount]
verify_jwt = false

[functions.get-categories]
verify_jwt = false

[functions.get-logs]
verify_jwt = false

[functions.no1logs-api]
verify_jwt = false

[functions.paymentpoint-create-account]
verify_jwt = false

[functions.paymentpoint-webhook]
verify_jwt = false

[functions.sms-verification]
verify_jwt = false

[functions.betasub-vtu]
verify_jwt = false
